# Generated by Django 4.2.7 on 2023-11-27 11:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vendor_name", models.CharField(default="", max_length=100)),
                ("contact_details", models.TextField()),
                ("address", models.TextField()),
                (
                    "vendor_code",
                    models.CharField(
                        default=uuid.uuid4, editable=False, max_length=36, unique=True
                    ),
                ),
                ("on_time_delivery_rate", models.FloatField()),
                ("quality_rating_avg", models.FloatField()),
                ("average_response_time", models.FloatField()),
                ("fulfillment_rate", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Purchase_order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("po_number", models.CharField(default="", max_length=100)),
                ("order_date", models.DateTimeField()),
                ("delivery_date", models.DateTimeField()),
                ("items", models.JSONField()),
                ("quantity", models.IntegerField()),
                ("status", models.CharField(default="", max_length=100)),
                ("quality_rating", models.FloatField()),
                ("issue_date", models.DateTimeField()),
                ("acknowledgment_date", models.DateTimeField()),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.vendor"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Hist_performance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hist_date", models.DateTimeField()),
                ("on_time_delivery_rate", models.FloatField()),
                ("quality_rating_avg", models.FloatField()),
                ("average_response_time", models.FloatField()),
                ("fulfillment_rate", models.FloatField()),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.vendor"
                    ),
                ),
            ],
        ),
    ]
